// @astrojs/sitemap doesn't allow filtering content collection items by their data properties, so I wrote this simple static file endpoint instead.
// see: https://docs.astro.build/en/core-concepts/endpoints/#static-file-endpoints

import { getPosts } from '../utils/posts'
import { getNotes } from '../utils/notes'
import { getBookmarks } from '../utils/bookmarks'
import { getDrafts } from '../utils/drafts'
import { getSinglePages } from '../utils/pages'

export async function GET(): Promise<Response> {
  const staticPages = ['/', '/likes/', '/notes/'] // paths generated by file names in src/pages
  const singlePages = await getSinglePages() // paths generated by [slug].astro
  const posts = await getPosts() // paths generated by [slug].astro
  const drafts = await getDrafts() // paths generated by [slug].astro
  const notes = await getNotes() // paths generated by [slug].astro
  const bookmarks = await getBookmarks() // paths generated by [slug].astro

  // all paths in /[slug]/ format
  const allPaths = [
    ...staticPages,
    ...singlePages.map(page => `/${page.id}/`),
    ...posts.map(post => `/${post.id}/`),
    ...drafts.map(draft => `/${draft.id}/`),
    ...notes.map(note => `/${note.id}/`),
    ...bookmarks.map(bookmark => `/${bookmark.id}/`),
  ]

  const xml = `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${allPaths
    .map(path => `<url><loc>${`https://michaeluloth.com${path}`}</loc></url>`)
    .join('')}</urlset>`

  return new Response(xml)
}
